Data Collection

In [2]:
list_data = [1, 2, 3, 4, 5, 6]

In [3]:
list_data

[1, 2, 3, 4, 5, 6]

In [5]:
list_data[0]

1

In [6]:
list_data[5]

6

In [8]:
list_data[0:3]

[1, 2, 3]

In [9]:
list_data[0:5:2]

[1, 3, 5]

Tugas Part A

In [13]:
var_a = [2, 1, 9, 1, 3, 4]
print(var_a[2])
print(var_a[1:4])
print([var_a[0],var_a[1],var_a[5]])

9
[1, 9, 1]
[2, 1, 4]


Tugas Part B

In [3]:
my_2d_list = [[1, 2, 3, 4, 5, 6, 3, 2, 1], [1, 2, 3, 4, 5, 6, 3, 2, 1], [1, 2, 3, 4, 5, 6, 3, 2, 1]]
my_list = [12, 21, 33, 45, 54, 62, 31, 23, 11]

#Nilai maksimum dari my_list
max_1d = max(my_list)
print('max_id: ', max_1d)

#Nilai minimum dari my_list
min_1d = min(my_list)
print('min_id: ', min_1d)

#Range data
data_range = max_1d - min_1d
print('data_range: ', data_range)

#Nilai rata-rata dari my_list
avg_1d = sum(my_list)/len(my_list)
print('mean: ', avg_1d)

#Hapus elemen 31 pada my_list
my_list.remove(31)
print('my_list: ', my_list)

#Tambahkan nilai 999 di akhir list
my_list.append(999)
print('my_list: ', my_list)

#Lakukan penjumlahan antara my_list dengan my_2d_list
combined_list = my_list + my_2d_list
print('combined_list: ', combined_list)

#Ubah nilai terakhir dari combined_list menjadi -999
combined_list[11] = -999
print('combined_list: ', combined_list)

max_id:  62
min_id:  11
data_range:  51
mean:  32.44444444444444
my_list:  [12, 21, 33, 45, 54, 62, 23, 11]
my_list:  [12, 21, 33, 45, 54, 62, 23, 11, 999]
combined_list:  [12, 21, 33, 45, 54, 62, 23, 11, 999, [1, 2, 3, 4, 5, 6, 3, 2, 1], [1, 2, 3, 4, 5, 6, 3, 2, 1], [1, 2, 3, 4, 5, 6, 3, 2, 1]]
combined_list:  [12, 21, 33, 45, 54, 62, 23, 11, 999, [1, 2, 3, 4, 5, 6, 3, 2, 1], [1, 2, 3, 4, 5, 6, 3, 2, 1], -999]


Tuple dan Set

In [7]:
var_a = (1, 2, 3, 1, 2, 3)
print(var_a)

(1, 2, 3, 1, 2, 3)


In [11]:
var_b = {1, 2, 3, 1, 2, 3}
print(var_b)
print(var_a[3])
print(var_a[3:5])
print(var_b[0])

{1, 2, 3}
1
(1, 2)


TypeError: 'set' object is not subscriptable

Operasi pada Tuple dan Set

In [13]:
var_a = (1, 2, 3, 1, 2, 3)
var_b = {1, 2, 3, 1, 2, 3}
print(var_a*2)
print(var_a + var_b)

(1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3)


TypeError: can only concatenate tuple (not "set") to tuple

Update Value Tuple dan Set

In [28]:
var_a = (3, 2, 1, 1, 2, 3)
var_b = {3, 2, 1, 1, 2, 3}
var_c = list(var_a)
var_c[5] = 999
var_a = tuple(var_c)
print(var_a)
var_d = list(var_b)
var_d[0] = 999
var_b = set(var_d)
print(var_b)

(3, 2, 1, 1, 2, 999)
{2, 3, 999}


Tugas Part C

In [45]:
var_a = (2,3,5,6,3,3,1,2,2,4,5,6,7)
print('var_a: ', var_a)
var_b = {2,3,5,6,3,3,1,2,2,4,5,6,7}
print('var_b: ', var_b)

var_c = list(var_a)
print('var_c: ', var_c)
var_d = list(var_b)
print('var_d: ', var_d)

var_c[3] = 999
print('var_c: ', var_c)
var_d[3] = 999
print('var_d: ', var_d)

var_a = tuple(var_c)
print('var_a: ', var_a)
var_b = set(var_d)
print('var_b: ', var_b)

var_b = set(var_d)
var_b

var_a:  (2, 3, 5, 6, 3, 3, 1, 2, 2, 4, 5, 6, 7)
var_b:  {1, 2, 3, 4, 5, 6, 7}
var_c:  [2, 3, 5, 6, 3, 3, 1, 2, 2, 4, 5, 6, 7]
var_d:  [1, 2, 3, 4, 5, 6, 7]
var_c:  [2, 3, 5, 999, 3, 3, 1, 2, 2, 4, 5, 6, 7]
var_d:  [1, 2, 3, 999, 5, 6, 7]
var_a:  (2, 3, 5, 999, 3, 3, 1, 2, 2, 4, 5, 6, 7)
var_b:  {1, 2, 3, 5, 6, 999, 7}


{1, 2, 3, 5, 6, 7, 999}

Dictionary

In [48]:
my_dict1 = {'nama': 'ashari'}
my_dict1

{'nama': 'ashari'}

In [49]:
my_dict2 = {'hobi': ['menggambar', 'bermusik']}
my_dict2

{':hobi': ['menggambar', 'bermusik']}

In [1]:
my_dict3 = {'nama': 'ashari', 'hobi': ['menggambar', 'bermusik']}
my_dict3['alamat']= 'Taman Kopo Indah'
print(my_dict3)

{'nama': 'ashari', 'hobi': ['menggambar', 'bermusik'], 'alamat': 'Taman Kopo Indah'}


Tugas Part D

In [8]:
#Buatlah sebuah dictionary yang berisi tiga keys dengan nama keys 'nama' 'nim' dan 'ttl' disimpan dalam variabel data_mhs
data_mhs = {'nama': '', 'nim': '', 'ttl': ''}
print(data_mhs)

#Masing-masing keys diisi dengan 5 nilai. Nama, nim, dan ttl diisi dengan nilai yang benar.
data_mhs['nama'] = ['ashari', 'yan', 'ucup', 'ato', 'tunggul']
print(data_mhs)

data_mhs['nim'] = ['101217006', '101217001', '101217009', '101217089', '101217090']
print(data_mhs)

data_mhs['ttl'] = ['18 Juli 1998', '23 Juni 1999', '17 Agustus 1997', '2 Mei 2000', '3 April 2001']
print(data_mhs)

#Tambah keys pada data_mhs dengan `kota_asal` yang diisi dengan kota asal mhs yang bersangkutan
data_mhs['kota_asal'] = ['Tulungagung', 'Surabaya', 'Jakarta Utara', 'Jakarta Selatan', 'Surabaya']
print(data_mhs)

{'nama': '', 'nim': '', 'ttl': ''}
{'nama': ['ashari', 'yan', 'ucup', 'ato', 'tunggul'], 'nim': '', 'ttl': ''}
{'nama': ['ashari', 'yan', 'ucup', 'ato', 'tunggul'], 'nim': ['101217006', '101217001', '101217009', '101217089', '101217090'], 'ttl': ''}
{'nama': ['ashari', 'yan', 'ucup', 'ato', 'tunggul'], 'nim': ['101217006', '101217001', '101217009', '101217089', '101217090'], 'ttl': ['18 Juli 1998', '23 Juni 1999', '17 Agustus 1997', '2 Mei 2000', '3 April 2001']}
{'nama': ['ashari', 'yan', 'ucup', 'ato', 'tunggul'], 'nim': ['101217006', '101217001', '101217009', '101217089', '101217090'], 'ttl': ['18 Juli 1998', '23 Juni 1999', '17 Agustus 1997', '2 Mei 2000', '3 April 2001'], 'kota_asal': ['Tulungagung', 'Surabaya', 'Jakarta Utara', 'Jakarta Selatan', 'Surabaya']}


Deklarasi Array

In [10]:
import numpy as np

In [14]:
var_a = [8, 6, 2, 3, 1, 4]
arr = np.array(var_a)
print(arr)

[8 6 2 3 1 4]


List Indexing, Slicing, dan Striding

In [20]:
my_arr = np.array([8, 6, 6, 2, 2, 3, 1, 4, 4])
my_arr[0]
print(my_arr[0])
my_arr[1:5]
print(my_arr[1:5])
my_arr[::2]
print(my_arr[::2])

8
[6 6 2 2]
[8 6 2 1 4]


Value Update pada Array

In [21]:
my_arr = np.array([8, 6, 6, 2, 2, 3, 1, 4, 4])
my_arr[0] = 999
print(my_arr)

[999   6   6   2   2   3   1   4   4]


Operasi Matematis pada Array

In [26]:
my_arr1 = np.array([1, 2, 3, 4, 5, 6, 6, 4, 3, 3, 2, 4])
my_arr2 = np.array([[1, 2, 3], [4, 5, 6], [6, 4, 3], [3, 2, 4]])
my_arr1 * 2
print(my_arr1 * 2)
print(my_arr2 * 3)

[ 2  4  6  8 10 12 12  8  6  6  4  8]
[[ 3  6  9]
 [12 15 18]
 [18 12  9]
 [ 9  6 12]]


Tugas Part E

In [27]:
import numpy as np

In [36]:
#Buatlah sebuah array dengan nilai [[6 0 7 4 0],[9 2 7 9 2],[5 3 3 0 1],[6 8 3 5 7]] pada variabel arr_a
arr_a = np.array([[6, 0, 7, 4, 0], [9, 2, 7, 9, 2], [5, 3, 3, 0, 1], [6, 8, 3, 5, 7]])
print('arr_a:', arr_a)

#Buatlah sebuah array dengan nilai [[8], [0], [2], [9]] pada variabel arr_b
arr_b = np.array([[8], [0], [2], [9]])
print('arr_b: ', arr_b)

#Buatlah sebuah array dengan nilai [8, 0, 2, 9] pada variabel arr_c
arr_c = np.array([8, 0, 2, 9])
print('arr_c: ', arr_c)

#Lakukan operasi penjumlahan antara arr_a dan arr_b
sum_ab = arr_a + arr_b
print('sum_ab: ', sum_ab)

print('arr_a: ', arr_a, 'arr_b: ', arr_b, 'arr_c: ', arr_c, 'sum_ab: ', sum_ab)

#Lakukan operasi penjumlahan antara arr_a dan arr_c
sum_ac = arr_a + arr_c
print('sum_ac: ', sum_ac)



arr_a: [[6 0 7 4 0]
 [9 2 7 9 2]
 [5 3 3 0 1]
 [6 8 3 5 7]]
arr_b:  [[8]
 [0]
 [2]
 [9]]
arr_c:  [8 0 2 9]
sum_ab:  [[14  8 15 12  8]
 [ 9  2  7  9  2]
 [ 7  5  5  2  3]
 [15 17 12 14 16]]
arr_a:  [[6 0 7 4 0]
 [9 2 7 9 2]
 [5 3 3 0 1]
 [6 8 3 5 7]] arr_b:  [[8]
 [0]
 [2]
 [9]] arr_c:  [8 0 2 9] sum_ab:  [[14  8 15 12  8]
 [ 9  2  7  9  2]
 [ 7  5  5  2  3]
 [15 17 12 14 16]]


ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

Operasi antara arr_a dan arr_c error karena masing-masing memiliki jumlah list yang berbeda (arr_a punya 4 list, sedangkan arr_c hanya 1 list)